### ISSUE TITLE
Aspect is not called for parent class methods.

### ISSUE THREAD

**Issue by NurimOnsemiro** [engelmi/ts-aspect#12]
## Describe the bug

I was expecting Aspect to be called on the parent class method as well, but it wasn't.

## To Reproduce

```typescript
import {Advice, Aspect, AspectContext, addAspectToPointcut} from 'ts-aspect'

class LogAspect implements Aspect {
  execute(ctx: AspectContext): void {
    console.log(ctx)
  }
}

class Calculator {
  add(a: number, b: number): number {
    return a + b
  }

  subtract(a: number, b: number): number {
    return a - b
  }

  divide(a: number, b: number): number {
    if (b === 0) {
      throw new Error('Division by zero!')
    }
    return a / b
  }

  multiply(a: number, b: number): number {
    return a * b
  }
}

class ChildCalculator extends Calculator {
  sum(arr: number[]): number {
    return arr.reduce((acc, val) => acc + val, 0)
  }
}

const calculator = new ChildCalculator()
addAspectToPointcut(calculator, '.*', Advice.After, new LogAspect())

calculator.sum([1,2,3,4,5]) // log ok
calculator.add(1,5) // no log printed
```

## Expected behavior

The log is displayed when the calculator.add method is called.

**Comment by engelmi** [comment]
Hi @NurimOnsemiro, thanks for opening this bug! I agree, it should apply the aspect also to the methods of the parent class(es). I prepared a small PR to fix this issue. Could you please have a look at #13 if it solves your issue?

**Comment by NurimOnsemiro** [comment]
Hi @engelmi , I tested with that branch in my local environment and observed that the sum method also works fine.

**Comment by engelmi** [comment]
@NurimOnsemiro 
Created a new release [v3.1.0](https://github.com/engelmi/ts-aspect/releases/tag/v3.1.0) and published to npm: https://www.npmjs.com/package/ts-aspect
Closing this issue.
