### ISSUE TITLE
Add original args when is AfterReturned

### ISSUE THREAD

**Issue by Arekushi** [engelmi/ts-aspect#3]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `ts-aspect@2.1.6` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/ts-aspect/build/proxyFunc.js b/node_modules/ts-aspect/build/proxyFunc.js
index 105fffa..7145388 100644
--- a/node_modules/ts-aspect/build/proxyFunc.js
+++ b/node_modules/ts-aspect/build/proxyFunc.js
@@ -48,7 +48,7 @@ function proxyFunc(target, methodContainer, ...args) {
     }
     if (adviceAspectMap.has(advice_enum_1.Advice.AfterReturn)) {
         (_g = adviceAspectMap.get(advice_enum_1.Advice.AfterReturn)) === null || _g === void 0 ? void 0 : _g.forEach(aspect => {
-            returnedValue = aspect.execute(target, [returnedValue]);
+            returnedValue = aspect.execute(target, [args, returnedValue]);
         });
     }
     return returnedValue;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by engelmi** [comment]
Hi  @Arekushi! 

I am glad this project is of use to you and thanks for your input! :) 

Please have a look at the small PR I created for this: https://github.com/engelmi/ts-aspect/pull/4

**Comment by Arekushi** [comment]
> Hi @Arekushi!
> 
> I am glad this project is of use to you and thanks for your input! :)
> 
> Please have a look at the small PR I created for this: #4

You're welcome. I'm using it for a bot project for Discord, so I thought the changes were pertinent.
