### ISSUE TITLE
Aspects get executed before the Promise is resolved

### ISSUE THREAD

**Issue by Manik-Jain** [engelmi/ts-aspect#6]
**Issue** : In case of an async-await event loop, any Aspects registered with 'AfterReturn' on the cut-point are invoked prior to the function returns after resolving the promise.

**Impact** :  Any results returned from the function are not acted upon as per the logic written inside the aspect code

**Expectation** : Aspect code must be called once the function has actually returned, not before during this is under execution.

**Comment by engelmi** [comment]
Hi @Manik-Jain, 
sorry for the late reply. 
Valid point, I will have a look at this the next days and investigate how to support aspects on async functions. If you have a solution already, I'd be happy if you can create a PR :)

**Comment by engelmi** [comment]
Created a [new release 2.3.0](https://github.com/engelmi/ts-aspect/releases/tag/2.3.0) which support async functions so that aspectes for advices After, AfterReturn and the second call of Around have access to the resolved Promise of the injected function.
