### ISSUE TITLE
 Cannot read properties of undefined (reading 'isAsyncFunction')

### ISSUE THREAD

**Issue by CodePirate7** [engelmi/ts-aspect#8]
<img width="789" alt="image" src="https://user-images.githubusercontent.com/35660919/170535924-99c39aff-30f7-4d56-8092-8cee09274810.png">

hi，How do I fix it？

**Comment by engelmi** [comment]
Hi @q389491729, which NodeJS version are you using? The `isAsyncFunction` is provided by the types import, which in turn requires a NodeJS version >15.3.0 (see [here](https://nodejs.org/api/util.html#utiltypes))

**Comment by engelmi** [comment]
I am closing this issue. If you have further questions, feel free to re-open it @q389491729
